[package]
name = "cpe5110-project"
version = "0.1.0"
edition = "2021"
default-run = "cpe5110-project"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
